/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_grp_assignment;
import java.io.BufferedReader;  
import java.io.FileReader;     
import java.io.IOException;    
import javax.swing.JLabel;     
import javax.swing.JOptionPane;
import java.util.Arrays;
/**
 *
 * @author HP
 */
public class residentspayment extends javax.swing.JFrame {
    private String username;
    private String tpNumber;
    private String password;
    private String rePassword;
    private String contact;
    private String eContact;
    private String email;
    private String dateBirth;
    private String address;
    private String country;
    private String roomType;
    private String referenceNum;
    private String roomNo;

    /**
     * Creates new form residentspayment
     */
    public residentspayment(){
        initComponents();
    }
    public residentspayment(String username, String tpNum, String password, String rePassword, String contact, String eContact, String email, String dateBirth, String address, String country, String roomType, String referenceNum, String roomNo) {
        this.username = username;
        this.tpNumber = tpNum;
        this.password = password;
        this.rePassword = rePassword;
        this.contact = contact;
        this.eContact = eContact;
        this.email = email;
        this.dateBirth = dateBirth;
        this.address = address;
        this.country = country;
        this.roomType = roomType;
        this.referenceNum = referenceNum;
        this.roomNo = roomNo;
        initComponents();
        loadPaymentData(tpNum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        residentspaymentback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        decreceipt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        decamount = new javax.swing.JLabel();
        decstatus = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        janreceipt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        janamount = new javax.swing.JLabel();
        janstatus = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        febreceipt = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        febamaount = new javax.swing.JLabel();
        febstatus = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        marchreceipt = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        marchamount = new javax.swing.JLabel();
        marchstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(80, 118, 135));

        jPanel2.setBackground(new java.awt.Color(56, 75, 112));

        residentspaymentback.setText("BACK");
        residentspaymentback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentspaymentbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(residentspaymentback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(residentspaymentback)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your Payment Summary");

        jPanel3.setBackground(new java.awt.Color(245, 240, 213));

        decreceipt.setText("View Receipt");
        decreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreceiptActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Amount Payable :");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Status :");

        decamount.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        decamount.setText("jLabel10");

        decstatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        decstatus.setText("jLabel11");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(decreceipt)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decamount, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(decamount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decreceipt)
                    .addComponent(jLabel3)
                    .addComponent(decstatus))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(245, 240, 213));

        janreceipt.setText("View Receipt");
        janreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                janreceiptActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Amount Payable :");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Status :");

        janamount.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        janamount.setText("jLabel12");

        janstatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        janstatus.setText("jLabel13");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(janamount)
                        .addContainerGap(302, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(janstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(janreceipt)
                        .addGap(14, 14, 14))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(janamount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(janstatus)
                    .addComponent(janreceipt))
                .addGap(9, 9, 9))
        );

        jPanel5.setBackground(new java.awt.Color(245, 240, 213));

        febreceipt.setText("View Receipt");
        febreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                febreceiptActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Amount Payable :");

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Status :");

        febamaount.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        febamaount.setText("jLabel14");

        febstatus.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        febstatus.setText("jLabel15");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(febstatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(febreceipt)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(febamaount)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(febamaount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(febreceipt)
                    .addComponent(jLabel7)
                    .addComponent(febstatus))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(245, 240, 213));

        marchreceipt.setText("View Receipt");
        marchreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marchreceiptActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setText("Amount Payable :");

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setText("Status :");

        marchamount.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        marchamount.setText("jLabel16");

        marchstatus.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        marchstatus.setText("jLabel17");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(marchstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(marchreceipt)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(marchamount)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(marchamount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marchreceipt)
                    .addComponent(jLabel9)
                    .addComponent(marchstatus))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void decreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreceiptActionPerformed
        processReceiptAction("December 2024");
    }//GEN-LAST:event_decreceiptActionPerformed

    private void janreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_janreceiptActionPerformed
        processReceiptAction("January 2025");
    }//GEN-LAST:event_janreceiptActionPerformed

    private void febreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_febreceiptActionPerformed
        processReceiptAction("February 2025");
    }//GEN-LAST:event_febreceiptActionPerformed

    private void marchreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marchreceiptActionPerformed
        processReceiptAction("March 2025");
    }//GEN-LAST:event_marchreceiptActionPerformed
    
    private void processReceiptAction(String month) {
    try (BufferedReader br = new BufferedReader(new FileReader("userPayment.txt"))) {
        String line;
        String name = "", tpNum = "", amount = "", receipt = "", paymentMethod = "", paymentDate = "";
        String loggedInTPNum = this.tpNumber; 

        while ((line = br.readLine()) != null) {
            line = line.trim();

            if (line.startsWith("residentName:")) {
                name = line.substring("residentName:".length()).trim();
            } else if (line.startsWith("TP Num:")) {
                tpNum = line.substring("TP Num:".length()).trim();
            } else if (line.contains(month) && tpNum.equals(loggedInTPNum)) {
                amount = extractAmount(line);
                receipt = extractReceipt(line);
                paymentMethod = extractPaymentMethod(line);
                paymentDate = extractPaymentDate(line);

                if (paymentDate.equalsIgnoreCase("Date") || paymentDate.equalsIgnoreCase("NOT APPLICABLE")) {
                    JOptionPane.showMessageDialog(this, "No valid payment data available for " + month + ".");
                    return; 
                }

                break;
            }
        }

        if (name.isEmpty() || tpNum.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No payment data found for " + month + ".");
            return;
        }

        paymentreceipt pr = new paymentreceipt(
            username,           
            tpNumber,           
            password,           
            rePassword,         
            contact,            
            eContact,           
            email,              
            dateBirth,          
            address,            
            country,            
            roomType,           
            referenceNum,       
            roomNo,             
            amount,             
            receipt,            
            paymentMethod,      
            paymentDate,        
            month               
        );

        pr.setVisible(true);
        this.dispose();
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error reading payment details.");
    }
}
    
    private void residentspaymentbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentspaymentbackActionPerformed
        usermain_page up = new usermain_page(username, tpNumber, password, rePassword, contact, eContact, email, dateBirth, address, country, roomType, referenceNum, roomNo);
        up.setVisible(true);  
        this.dispose();  
       
    }//GEN-LAST:event_residentspaymentbackActionPerformed
    
    public void loadPaymentData(String tpNum) {
    tpNum = tpNum.trim();

    try (BufferedReader br = new BufferedReader(new FileReader("userPayment.txt"))) {
        String line;
        boolean userFound = false;

        System.out.println("Reading file...");

        while ((line = br.readLine()) != null) {

            line = line.trim();

            System.out.println("Line read: '" + line + "'");

            if (line.startsWith("TP Num:")) {
                String lineTpNum = line.substring("TP Num:".length()).trim();
                System.out.println("Comparing TP Num: '" + tpNum + "' with '" + lineTpNum + "'");

                if (lineTpNum.equals(tpNum)) {
                    System.out.println("Found user with TP Num: " + tpNum);
                    userFound = true;

                    displayPaymentDetails(br);
                    break; 
                }
            }
        }

        if (!userFound) {
            System.out.println("User not found in file.");
            JOptionPane.showMessageDialog(null, "No payment data found for TP Num: " + tpNum);
        }
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error loading payment data.");
    }
}

    private void displayPaymentDetails(BufferedReader br) throws IOException {
    String line;

    while ((line = br.readLine()) != null && !line.trim().isEmpty()) {
        if (line.contains("December 2024:")) {
            updateMonthStatus(line, decamount, decstatus);
        } else if (line.contains("January 2025:")) {
            updateMonthStatus(line, janamount, janstatus);
        } else if (line.contains("February 2025:")) {
            updateMonthStatus(line, febamaount, febstatus);
        } else if (line.contains("March 2025:")) {
            updateMonthStatus(line, marchamount, marchstatus);
        }
    }
}

    private void updateMonthStatus(String line, JLabel amountLabel, JLabel statusLabel) {
     String amount = extractAmount(line);
    String receipt = extractReceipt(line);
    String paymentMethod = extractPaymentMethod(line);
    String paymentDate = extractPaymentDate(line);

    System.out.println("Processing Line: " + line);
    System.out.println("Extracted Amount: " + amount);
    System.out.println("Extracted Receipt: " + receipt);
    System.out.println("Extracted Payment Method: " + paymentMethod);
    System.out.println("Extracted Payment Date: " + paymentDate);

    if (paymentDate.equalsIgnoreCase("NOT APPLICABLE")) {
        amountLabel.setText("NOT APPLICABLE"); 
        statusLabel.setText("NOT APPLICABLE"); 
        System.out.println("Payment Date NOT APPLICABLE: Amount and Status set to '-'");
        return; 
    }

    amountLabel.setText(amount);

    if (receipt.isEmpty() || paymentMethod.equalsIgnoreCase("None")) {
        System.out.println("Setting Status: Pending");
        statusLabel.setText("PENDING"); 
    } else {
        System.out.println("Setting Status: Paid");
        statusLabel.setText("PAID"); 
    }
}

    private String extractAmount(String line) {
    String[] parts = line.split(":");
    if (parts.length > 1) {
        String[] subParts = parts[1].trim().split(" ");
        if (subParts.length > 0) {
            return subParts[0].trim();
        }
    }
    return "-";
}

    private String extractReceipt(String line) {
        if (line.contains("[RECEIPT-")) {
            int start = line.indexOf("[RECEIPT-") + "[RECEIPT-".length();
            int end = line.indexOf("]", start);
            if (start < end) {
                String receipt = line.substring(start, end).trim();
                System.out.println("Extracted Receipt: '" + receipt + "'");
                return receipt.equals("") ? "" : receipt;
            }
        }
        System.out.println("Receipt Not Found");
        return ""; 
    }

    private String extractPaymentMethod(String line) {
    if (line.contains("[") && line.contains("]")) {
        String[] parts = line.split("\\[");
        for (String part : parts) {
            if (part.contains("CASH") || part.contains("BANK TRANSFER") || part.contains("CREDIT CARD") || part.contains("None")) {
                String method = part.split("]")[0].trim();
                System.out.println("Extracted Payment Method: '" + method + "'");
                return method;
            }
        }
    }
    System.out.println("Payment Method Not Found");
    return "None"; 
}
    
    private String extractPaymentDate(String line) {
    int start = line.lastIndexOf("[") + 1;
    int end = line.lastIndexOf("]");
    return (start > 0 && end > start) ? line.substring(start, end) : "Date";
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
      
        javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    java.awt.EventQueue.invokeLater(() -> {
        new residentspayment(
            "AAA",            
            "000001",          
            "password123",     
            "password123",     
            "123456789",       
            "987654321",      
            "admin@example.com", 
            "2000-01-01",      
            "123 Main St",     
            "CountryName",     
            "Single Room",    
            "REF12345",        
            "101"            
        ).setVisible(true);
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel decamount;
    private javax.swing.JButton decreceipt;
    private javax.swing.JLabel decstatus;
    private javax.swing.JLabel febamaount;
    private javax.swing.JButton febreceipt;
    private javax.swing.JLabel febstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel janamount;
    private javax.swing.JButton janreceipt;
    private javax.swing.JLabel janstatus;
    private javax.swing.JLabel marchamount;
    private javax.swing.JButton marchreceipt;
    private javax.swing.JLabel marchstatus;
    private javax.swing.JButton residentspaymentback;
    // End of variables declaration//GEN-END:variables
}
