/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_grp_assignment;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



public class staff_payment2 extends javax.swing.JFrame {
    private String TPNumber;
    private String Name;
    private String Month;
    private String roomType;
    private String roomNum;
    private String registrationDate;
    private String TotalAmount;
    private int receiptNum = 000000;

    private String staffname;
    private String tpNum;
    private String Password;
    private String email;
    private String contact;
    
    public staff_payment2() {
        initComponents();
    }
                                                                                                                                                                                                                                                                                                                            
    public staff_payment2(String staffname, String staffTPNum, String Password, String email, String contact, String tpNum, String name, String month, String amount, String roomtype, String roomnumber, String registrationdate){
        initComponents();
        this.staffname = staffname;
        this.tpNum = staffTPNum;
        this.Password = Password;
        this.email = email;
        this.contact = contact;
        
        this.TPNumber = tpNum;
        this.Name = name;
        this.Month = month;
        this.TotalAmount = amount;
        this.roomType = roomtype;
        this.roomNum = roomnumber;
        this.registrationDate = registrationdate;
        
        ap2_tpNum.setText(TPNumber);
        ap2_name.setText(Name);
        ap2_selectedMonth.setText(Month);
        ap2_totalAmount.setText(TotalAmount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ap2_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ap2_tpNum = new javax.swing.JTextField();
        ap2_name = new javax.swing.JTextField();
        ap2_selectedMonth = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ap2_day = new javax.swing.JTextField();
        ap2_Month = new javax.swing.JTextField();
        ap2_year = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ap2_totalAmount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ap2_paymentMethod = new javax.swing.JComboBox<>();
        ap2_confirmbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(80, 118, 135));

        jPanel2.setBackground(new java.awt.Color(56, 75, 112));
        jPanel2.setPreferredSize(new java.awt.Dimension(92, 52));

        ap2_back.setText("Back");
        ap2_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap2_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ap2_back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ap2_back)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setText("TP Number:");

        jLabel2.setText("Name:");

        jLabel3.setText("Selected Month:");

        jLabel4.setText("Payment Date:");

        jLabel5.setText("/");

        jLabel6.setText("/");

        jLabel7.setText("DD");

        jLabel8.setText("MM");

        jLabel9.setText("YYYY");

        jLabel10.setText("Total Fees Amount:");

        jLabel11.setText("Payment Method:");

        ap2_paymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credit Card", "Cash", "Online Transaction" }));

        ap2_confirmbtn.setText("Confirm");
        ap2_confirmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap2_confirmbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ap2_confirmbtn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ap2_totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ap2_paymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel7))
                                .addComponent(ap2_day, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ap2_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel8)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel9))
                                .addComponent(ap2_year, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ap2_name, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ap2_tpNum, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ap2_selectedMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ap2_tpNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ap2_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ap2_selectedMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ap2_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ap2_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ap2_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ap2_totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(ap2_paymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(ap2_confirmbtn)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ap2_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap2_backActionPerformed
        staff_payment ap = new staff_payment(staffname, tpNum, Password, email, contact);
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ap2_backActionPerformed

    private void ap2_confirmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap2_confirmbtnActionPerformed
        String paymentDate = ap2_day.getText() + "-" + ap2_Month.getText() + "-" + ap2_year.getText();
        String paymentMethod = (String) ap2_paymentMethod.getSelectedItem();
        String year = "";

        
        try{
            BufferedReader reader = new BufferedReader(new FileReader("userPayment.txt"));
            List<String> allUserInfo = new ArrayList<>();
            String userLines;
            boolean userAreaFound = false;
            boolean userFound = false;
            int highestReceiptNum = 0;
            
            while ((userLines = reader.readLine()) != null) {
                if (userLines.contains("RECEIPT-")) {
                    String[] parts = userLines.split("RECEIPT-");
                    if (parts.length > 1) {
                        try {
                            int currentReceiptNum = Integer.parseInt(parts[1].split("]")[0].trim());
                            highestReceiptNum = Math.max(highestReceiptNum, currentReceiptNum);
                            
                            String paymentLines = parts[0].trim();
                            String[] monthYear = paymentLines.split(":")[0].trim().split(" ");
                            year = monthYear[1];
                            
                        } catch (NumberFormatException e) {
                            // Skip invalid receipt numbers
                        }
                    }
                }
            }
            
            reader.close();
            reader = new BufferedReader(new FileReader("userPayment.txt"));

            while ((userLines = reader.readLine()) != null) {
                System.out.println("reach here");
                if (userLines.startsWith("TP Num:")) {
                    userAreaFound = userLines.substring(8).trim().equalsIgnoreCase(TPNumber.trim());
                    allUserInfo.add(userLines); 
                    if (userAreaFound) {
                        userFound = true;
                    }
                } else if (userAreaFound && userLines.startsWith("Payments:")) {
                    StringBuilder updatedPayments = new StringBuilder("Payments:\n");
                    boolean paymentUpdated = false;
                    System.out.println("reach here 02");
                    while ((userLines = reader.readLine()) != null && !userLines.startsWith("TP Num:")) {
                        System.out.println(Month);
                        if (userLines.contains(Month)) {
                            System.out.println("reach here 03");
                            updatedPayments.append(Month).append(" ").append(year).append(": ").append(TotalAmount).append(" [RECEIPT-")
                                    .append(String.format("%06d", highestReceiptNum + 1)) //the format is to make the receipt number = 000001
                                    .append("] [").append(paymentMethod).append("] [")
                                    .append(paymentDate).append("]\n");
                            paymentUpdated = true;
                            System.out.println(updatedPayments);
                        } else {
                            updatedPayments.append(userLines).append("\n");
                        }
                    }

                    allUserInfo.add(updatedPayments.toString().trim());

                    if (userLines != null && userLines.startsWith("TP Num:")) {
                        allUserInfo.add(userLines);
                        userAreaFound = false;
                    }
                } else {
                    allUserInfo.add(userLines);
                }
            }

            reader.close();
            
            if(!userFound){
                JOptionPane.showMessageDialog(this, "User not Found: "+ TPNumber + " - "+ Name);
            }else{
                BufferedWriter writer = new BufferedWriter(new FileWriter("userPayment.txt"));
                for (String updatedLine : allUserInfo) {
                    System.out.println(updatedLine);
                    writer.write(updatedLine);
                    writer.newLine();
                }
                writer.close();
                
                System.out.println("Payment updated successfully.");//debug
                
                payment_receipt pr = new payment_receipt(Name,TPNumber,highestReceiptNum + 1,Month,TotalAmount,paymentMethod, paymentDate);
                pr.setVisible(true);
                this.dispose();
            }
            
        } catch (IOException ex) {
            Logger.getLogger(staff_payment2.class.getName()).log(Level.SEVERE, null, ex);
        }                 
                   
                
                
                
    }//GEN-LAST:event_ap2_confirmbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff_payment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff_payment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff_payment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff_payment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff_payment2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ap2_Month;
    private javax.swing.JButton ap2_back;
    private javax.swing.JButton ap2_confirmbtn;
    private javax.swing.JTextField ap2_day;
    private javax.swing.JTextField ap2_name;
    private javax.swing.JComboBox<String> ap2_paymentMethod;
    private javax.swing.JTextField ap2_selectedMonth;
    private javax.swing.JTextField ap2_totalAmount;
    private javax.swing.JTextField ap2_tpNum;
    private javax.swing.JTextField ap2_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
